### ISSUE TITLE
Error trying to create project

### ISSUE THREAD

**Issue by RodrigoBalest** [neutralinojs/neutralinojs-cli#117]
**Expected Behavior**  
New Neutralinojs project created at destination folder
  
**Actual Behavior**  
No project created. Error message is shown (see below)

**Steps to Reproduce the Problem**  
 1. Run `npx @neutralinojs/neu create myapp --template  neutralinojs/neutralinojs-zero`

**Specifications**  
* NeutralinoJs Version: Don't know, project not created
* NeutralinoJs CLI version: v9.2.0
* Platform: Windows 10 (running behind a corporate proxy)

**Detailed description**
When the command is run, the following is shown in the console:
```
λ npx @neutralinojs/neu create myapp --template  neutralinojs/neutralinojs-zero
neu: INFO Downloading neutralinojs/neutralinojs-zero template to myapp directory...
node:events:505
      throw er; // Unhandled 'error' event
      ^

Error: connect ETIMEDOUT 20.201.28.151:443
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1187:16)
Emitted 'error' event on Writable instance at:
    at ClientRequest.eventHandlers.<computed> (C:\Users\winuser\Desktop\_temp\node_modules\follow-redirects\index.js:14:24)
    at ClientRequest.emit (node:events:527:28)
    at TLSSocket.socketErrorListener (node:_http_client:442:9)
    at TLSSocket.emit (node:events:527:28)
    at emitErrorNT (node:internal/streams/destroy:164:8)
    at emitErrorCloseNT (node:internal/streams/destroy:129:3)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  errno: -4039,
  code: 'ETIMEDOUT',
  syscall: 'connect',
  address: '20.201.28.151',
  port: 443
}

Node.js v17.7.1
```

When I check the IP address 20.201.28.151 at the browser, a SSL_ERROR_BAD_CERT_DOMAIN error is issued. The message says the certificate is valid for the following domains: `github.com`, `www.github.com`.

I believe nodejs' `https.get()` method is for some reason translating the template's URL to the IP, but the IP and certificate don't match.

**Comment by Jassi10000** [comment]
@RodrigoBalest Hey buddy I think you should prefer the general way

The best way I tried is I installed the  <code>neu</code> first and then ran this command 

<code> neu create myapp --template neutralinojs/neutralinojs-zero </code> and my app was ready in 2 seconds 

Talking about the issue opened , I ran the same command and it's working fine in my system 
I hope you haven't created a folder named as <code> myapp </code> already 
Try creating a new project with a new name and tell if the same error comes coz am not getting any errors in both cases

**Comment by Jassi10000** [comment]
@RodrigoBalest Hey buddy , what's the update , were you able to overcome the issue or you need any assisstance ?

**Comment by RodrigoBalest** [comment]
Hi @Jassi10000 ! Thanks for your help!

I tried what you said but it didn't worked. I believe there's something to do with the corporate proxy on my network.

I will try it later in my home PC then I'll update the issue.

**Comment by Jassi10000** [comment]
Cool buddy !!! take ur time
One last thing I want you to test out 

Try to install <code>neu</code> in admistrator mode by running cmd on admin / u can do on powershell as well if you are using Windows.

and then excecute the other commands in a normal way in terminal 
Just try installing <code>neu</code> in the admin 
Do leme know what do you encounter now ?

Do reach out to me if you encounter any issues buddy

**Comment by pathange-s** [comment]
@RodrigoBalest yes, as you said, there are some hookups with corporate proxy and that's probably the error. And, I am sure this should have worked on your local home environment.

**Comment by RodrigoBalest** [comment]
@Jassi10000 I tried installing `neu` as admin but it didn't work too.
@pathange-s I tried it running in my home PC and it really worked fine, as you said.
Sure it's related to how our corporate firewall deals with nodejs requests. I think it translates URLs to its IP address.

Thank you both so much for your help!

**Comment by pathange-s** [comment]
@RodrigoBalest Great ! Tested this on my brother's intern's laptop, and same result, didn't work.
Please /* Corporate Proxy */

@shalithasuranga also, we can try figuring out what the issue boils down to and then, try to fix it if possible. 

@RodrigoBalest Will be glad if you can elaborate more on what corporate proxy is. I just have a very basic idea of it.

**Comment by RodrigoBalest** [comment]
@pathange-s Quoting Wikipedia (I couldn't explain it better):

> In computer networking, a proxy server is a server application that acts as an intermediary between a client requesting a resource and the server providing that resource.

It's used to cache responses, making them faster, and also to block some requests, restricting access so some services (for example, social networks).

I refer as corporate proxy because it is used by all of the corporate network, enforcing company's security policies.

**Comment by pathange-s** [comment]
Ah, gotcha ! Thanks @RodrigoBalest
