### ISSUE TITLE
Add description to neu-cli commands for better readability and UX

### ISSUE THREAD

**Issue by pathange-s** [neutralinojs/neutralinojs-cli#118]
Currently neu-cli tool lists commands that can be run.

For example:  `neu --help` outputs

 ```
 Usage: neu [options] [command]

Options:
  -h, --help                     display help for command

Commands:
  create [options] <binaryName>
  run [options]
  build [options]
  update
  version
  plugins [options] [plugin]
  help [command]                 display help for command
```
With increasing number of commands, at some point of time, there will be a need to have a short hand description for every command to help developers run CLI tool without need to refer to documentation every single time.
To UX better, we need to implement a minimal yet completely describable description for existing commands and also, for flags of each command. Also, new commands and plugins being introduced to the CLI tool should come with description describing what it does.

For reference : This CLI tool has better UX.

![image](https://user-images.githubusercontent.com/76244077/158820621-897ac4fb-a41d-4adf-9c0d-c2856b7fe178.png)

**Comment by shalithasuranga** [comment]
Hey @pathange-s  it's a great idea, feel free to send a pull request with these descriptions. Make sure to use some minimal descriptions as you showed in the example. Thanks :+1:
