### ISSUE TITLE
Error when building js template out-of-the-box

### ISSUE THREAD

**Issue by Zenahr** [neutralinojs/neutralinojs-cli#12]
Steps to reproduce:
enter following commands into command-line:
neu create hello_world_app --template js
cd hello_world_app && neu build
run neutralino-win.exe

Am I missing something here? I did install the npm dependencies and built the project again yielding the same result.

However replacing the index.html, app.css and app.js files inside /app with the code shown at https://neutralino.js.org/docs/#/gettingstarted solves the problem

![image](https://user-images.githubusercontent.com/47085752/80486513-96028c00-895b-11ea-84f4-7ebc578a6823.png)

**Comment by shalithasuranga** [comment]
This is fixed in v2
