### ISSUE TITLE
Configure and enfore project wide coding styles

### ISSUE THREAD

**Issue by YashKumarVerma** [neutralinojs/neutralinojs-cli#129]
## Current Implementation
the code lacks any consistent coding style and does not follow any specific linting rule, because of this:
1. different sections of code have different styles followed
2. common and proven practices might be missed as the development is done by different devs.

## Solution
1. setup a linter that follows any standard coding style (what matches with the project with minimal changes)
2. setup a code formatter that's supported by most editors (prettier, for example)
3. setup pre-commit hooks that run the linter and formatter on the staged files to automatically enfore the linter and formatter for all commits.
4. integrate the checks in the CI workflow

---
I'd be interested in implementing the same across the project repositories (also in sister repos)

**Comment by shalithasuranga** [comment]
Thanks so much for posting this idea @YashKumarVerma. Closing this issue since now we have a code formatting tool integrated with this project :tada:
