### ISSUE TITLE
"testNeuCli" isn't deleted after test script is run

### ISSUE THREAD

**Issue by NethmiRodrigo** [neutralinojs/neutralinojs-cli#138]
The directory created for testing in `test_commands.sh`, isn't deleted after the script is done running.
This causes an error if the script is run again because `mkdir testNeuCLI` fails since the directory is still there.

**Comment by pathange-s** [comment]
It was present in the code. Check [here](https://github.com/neutralinojs/neutralinojs-cli/pull/125/commits/819e17d65ea4773e0a076a93077ca07874ac7103). But I dont understand how it disappeared. It was removed for some reason in between commits and was thought to be added later.
Thanks for reminding it. Updated it [here](https://github.com/neutralinojs/neutralinojs-cli/pull/128/commits/441f0736e68cb46550a840201ebd586cd0028c33)

**Comment by NethmiRodrigo** [comment]
Awesome! I'll close this issue then.
