### ISSUE TITLE
"npm run test" command isn't compatible on Windows

### ISSUE THREAD

**Issue by NethmiRodrigo** [neutralinojs/neutralinojs-cli#139]
![image](https://user-images.githubusercontent.com/34070216/162607555-f79676a7-451d-4747-b9d0-fbbe4cffa049.png)
Running `npm test` causes the following error.
![image](https://user-images.githubusercontent.com/34070216/162607583-9ffe663e-2928-4727-9081-d63661f98f6c.png)
Changing the command to `bash scripts/test_commands.sh` would work on windows but not sure what effect it would leave on the workflow and other operating systems.

**Comment by pathange-s** [comment]
You can try testing it in your forked repository and update on the same.
Usually, workflows are defined separately for different OS. The current workflow for the CLI tool runs on `ubuntu` and the written workflow is correct. This issue (not an issue actually) will be addressed when someone writes CI CD workflow to run tests on Windows OS. That developer has to modify it in such a way that it runs smoothly.

**Comment by NethmiRodrigo** [comment]
> You can try testing it in your forked repository and update on the same. Usually, workflows are defined separately for different OS. The current workflow for the CLI tool runs on `ubuntu` and the written workflow is correct. This issue (not an issue actually) will be addressed when someone writes CI CD workflow to run tests on Windows OS. That developer has to modify it in such a way that it runs smoothly.

Actually, I'm not at all referring to the written workflow. I'm referring to the command and the command only, that runs the test script. Keeping the CI/CD workflow aside, if the above command is meant to be used to be run on a workflow only, then yes this wouldn't be an issue.

**Comment by HasinduLanka** [comment]
@pathange-s  @NethmiRodrigo 
I've made pull request #148 to make some progress for this issue. Can you look into it?

**Comment by shalithasuranga** [comment]
Closing this since now we use a new test suite. Thanks all for working on this 🎉
