### ISSUE TITLE
libstdc++.s0.6 incompatibility

### ISSUE THREAD

**Issue by SalihuDickson** [neutralinojs/neutralinojs-cli#140]
the app template build with the cli  or more of its dependencies seems to be dependent on a specific version of libstdc++  and will not work with any other versions. which causes a big problem for some linux distros that don't come with that version and it is also really difficult to find online.

Here is a screenshot of the error i get due to the incompatibility
![Screenshot 2022-04-12 2 14 17 PM](https://user-images.githubusercontent.com/91833785/162970756-d86519c9-1bae-43c8-9e02-c489898d6992.png)
:

**Comment by legendarykamal** [comment]
I confirm that this incompatibility problem is with linux version only , the windows version of cli works as expected.

**Comment by SalihuDickson** [comment]
> I confirm that this incompatibility problem is with linux version only , the windows version of cli works as expected.

Yeah it's only  problem on some linux systems

**Comment by shalithasuranga** [comment]
Hey all.. thanks for reporting and discussing this issue -- this issue was fixed with the latest release, now we compiled with a lower GCC version, so older libstd++ will be used. Really appreciate if you could test the latest version ;)

Thanks
