### ISSUE TITLE
libayatana-appindicator3-1 incompatibility

### ISSUE THREAD

**Issue by SalihuDickson** [neutralinojs/neutralinojs-cli#141]
The app build template built with the neutralino cli or it's dependencies is somewhat dependent on an older version of libayatana-appindicator, which is sometimes a problem mostly for debian distros which as far as i understand some use an alternative to libayatana-appindicator. I was able to resolve the problem but getting this specific version of libayatana-appindicator was no walk in the park.

Anyone that encounters this problem should try:
sudo apt-get update
sudo apt-get install libayatana-appindicator3-1

that resolved my problem but i think it will be a good idea to build the cli to work with less version dependent dependencies or at least use alternatives so more people can use it more easily.

**Comment by shalithasuranga** [comment]
Closing this issue since now we dynamically load this dependency :) Thanks for posting this issue :tada:
