### ISSUE TITLE
App directory containing incomplete files after an unsuccessful neu create

### ISSUE THREAD

**Issue by Ayman161803** [neutralinojs/neutralinojs-cli#142]
### Problem

An unsuccessful attempt to create a Neutralinojs project leaves behind a project directory containing incomplete files. The user will have to delete this project directory and only then run ``neu create <appname>`` to create a project with the same name again. Refer #123  

### Possible fix

Delete the project directory when ``neu create`` is unsuccessful. This can be done by adding ```        fs.rmdirSync(`../${binaryName}`, { recursive: true });``` [here](https://github.com/neutralinojs/neutralinojs-cli/blob/aa837846763056008680c315f00d68f693a613a7/src/modules/creator.js#L27)

**Comment by pathange-s** [comment]
Sure, go ahead. Easy fix, it is.

**Comment by Yash-271120** [comment]
@pathange-s please review (#168)

**Comment by shalithasuranga** [comment]
Closing this issue since #168 was merged. Thanks :tada:
