### ISSUE TITLE
libwebkit2gtk-4.0.so.37 incompatibility

### ISSUE THREAD

**Issue by kamalbuilds** [neutralinojs/neutralinojs-cli#149]
Bug
###  **Operating System-inux**

While running neu run Cli command it shows the following error code 
```
neu: INFO Starting process: neutralino-linux_x64  --load-dir-res --path=. --export-auth-info --neu-dev-extension --neu-dev-auto-reload
bin/neutralino-linux_x64: error while loading shared libraries: libwebkit2gtk-4.0.so.37: cannot open shared object file: No such file or directory
neu: WARNING neutralino-linux_x64 was stopped with error code 127
```
Hence, the app is unable to run.

**Comment by pathange-s** [comment]
I was facing similar issues in this [PR](https://github.com/neutralinojs/neutralinojs-cli/runs/5805113414?check_suite_focus=true#step:7:202). I fixed the gtk errors by installing the `libwebkit2gtk-4.0-37` package.

**Comment by legendarykamal** [comment]
Oh thanks for the update , but how did u install it as an npm package?

**Comment by legendarykamal** [comment]
Also, I was thinking of some way of making this inbuilt in neutralino so that dev don't have to manually install it @pathange-s !

**Comment by pathange-s** [comment]
Not everyone faces this. I faced this while running GitHub actions (its very unusual). You can just install using `apt` package manager.

**Comment by legendarykamal** [comment]
Ok might be

**Comment by shalithasuranga** [comment]
Closing this issue since now we dynamically load this dependency :) Thanks for posting this issue and starting a discussion :tada:

**Comment by vcarel** [comment]
Hi, I'm new to neutralino and I just got this issue.
I'm on node v20, Fedora 40, and I installed neutralino cli by npm

```
npm install -g @neutralinojs/neu
neu create test
cd test
neu run

neu: INFO Starting process: neutralino-linux_x64  --load-dir-res --path=. --export-auth-info --neu-dev-extension --neu-dev-auto-reload
bin/neutralino-linux_x64: error while loading shared libraries: libwebkit2gtk-4.0.so.37: cannot open shared object file: No such file or directory
neu: WARN neutralino-linux_x64 was stopped with error code 127
```
