### ISSUE TITLE
Unexpected plugin errors

### ISSUE THREAD

**Issue by Ayman161803** [neutralinojs/neutralinojs-cli#152]
It looks like my appify plugin is broken and I  get ``unable to load appify plugin`` after each neu CLI command. I removed appify plugin through ``neu CLI plugins --remove`` as well but it doesn't look like that is making any difference. 

Here is a screenshot which tries to explain the same.

![image](https://user-images.githubusercontent.com/76606666/164980893-233b2b51-c14b-45bb-8ad5-1aec7f3d69f1.png)

**Comment by gaurav-nelson** [comment]
I see the same error in macOS 12.3.1 (21E258)

```
❯❯ neu version
neu: ERROR Unable to load @neutralinojs/appify plugin.
  _   _            _             _ _             _
 | \ | | ___ _   _| |_ _ __ __ _| (_)_ __   ___ (_)___
 |  \| |/ _ \ | | | __| '__/ _` | | | '_ \ / _ \| / __|
 | |\  |  __/ |_| | |_| | | (_| | | | | | | (_) | \__ \
 |_| \_|\___|\__,_|\__|_|  \__,_|_|_|_| |_|\___// |___/
                                              |__/
--- Global ---
neu CLI: v9.3.0

--- Project: test-cmd-app (js.neutralino.sample) ---
Neutralinojs binaries: v4.5.0
Neutralinojs client: v3.4.0
Project version: v1.0.0
```

The app seems to run with no issues though.
```
❯❯ neu run
neu: ERROR Unable to load @neutralinojs/appify plugin.
neu: INFO Starting process: neutralino-mac_x64  --load-dir-res --path=. --export-auth-info --neu-dev-extension --neu-dev-auto-reload
INFO 2022-05-13 10:46:39,759 Auth info was exported to ./.tmp/auth_info.json api/debug/debug.cpp:14 ganelson@unknown-host
neu: INFO neu CLI connected with the application.
```

**Comment by Sadaf-A** [comment]
@Ayman161803 @gaurav-nelson Is this issue still persistent I just tried it on my side and everything seems to work fine

**Comment by Sadaf-A** [comment]
Hey @shalithasuranga , 
Since this has already been resolved I think this issue can be closed

**Comment by shalithasuranga** [comment]
Sure we can close this issue @Sadaf-A, thanks for the reminder :tada:
