### ISSUE TITLE
Running `neu build` after `new run --frontend-lib-dev` creates resources with hardcoded port.

### ISSUE THREAD

**Issue by yulolimum** [neutralinojs/neutralinojs-cli#153]
I followed the [instructions on this page](https://neutralino.js.org/docs/how-to/use-a-frontend-library#configuring-the-frontend-app) to create a Neutralino application with react. 

When running `new run --frontend-lib-dev` - everything works as expected. The `index.html` file is patched with the [current random port](https://user-images.githubusercontent.com/1775841/165185964-11663dab-77bc-44d0-94af-02fb17f0718d.jpg).

However, after running `new run build`, that "patched" `index.html` file remains with the hardcoded host/port since `neu` never changes it back to `%PUBLIC_URL%`.

Running the produced binary results in a white page. 

---

## Potential Solutions:

- In the documentation for front-end configuration, add a section that instructs the developer to set a static port in the `neutralino.config.js`. Having a static port will work with the patched file in both `run` and `build` commands.
- When running with the `--frontend-lib-dev` flag, detect when the process ends and "unpatch" the `patchFile`. 
- When running the `build` command, if `frontendLibrary.patchFile` is set, "unpatch" it.

Not sure what the best solution is - I'm fairly new to Neutralino!

**Comment by yulolimum** [comment]
I see there's already an attempt at doing so here: https://github.com/neutralinojs/neutralinojs-cli/blob/3ec5006ef634f9a047ff8d365b1bd3b119dd30e8/src/modules/frontendlib.js#L52-L57

Maybe this is unreleased? 

Let me know if this is already supposed to be working and I can do some debugging within the CLI.

**Comment by shalithasuranga** [comment]
Closing this since this issue doesn't occur with new releases. Please close the Neutralinojs app and let CLI to run the above mentioned cleanup code. Thanks for reporting this :tada:
