### ISSUE TITLE
Build Error -- neu: ERROR Error: ENOENT: no such file or directory, stat './undefined'

### ISSUE THREAD

**Issue by CM-IV** [neutralinojs/neutralinojs-cli#158]
# The Problem

I am running into an error when trying to build a GUI app that makes use of Preact Typescript and uses the Vitejs bundler on the frontend.

![image](https://user-images.githubusercontent.com/44551614/170588961-9db6e9c1-3778-4ac5-9622-4685c34a5ff8.png)

This error does not really tell me much, and the `neutralinojs.log` file does not show a relevant ERROR either.

A temp folder is generated after building that holds the resources dir and the neu.config.json file:

![image](https://user-images.githubusercontent.com/44551614/170589227-b41d9b8f-543d-4892-8f66-4dbbbd2b05a5.png)

Inside of my frontend `package.json`, I am copying over the built files into the `resources` dir:

![image](https://user-images.githubusercontent.com/44551614/170589299-f90a8042-b1b9-4ace-8edc-f79835d51983.png)

This is what the inside of my index.html file looks like:

![image](https://user-images.githubusercontent.com/44551614/170589719-d88e32ce-43a7-495c-991f-b8a7c3afcd8a.png)

I was able to use the neu cli to create the minimal project and build it successfully that way, which is why there is a `dist` directory at the top level.

The GUI is able to hot reload properly with the help of Vitejs, but I cannot figure out this one issue that prevents me from building.

**Comment by CM-IV** [comment]
[Here](https://privatebin.net/?6b186d5714473af2#7t8Z4UPzfhhq63AiRWFoUSfCGWFtYTbg4EwUWziZLWnV) are the contents of the `neutralino.config.json`:

**Comment by Saeid-Za** [comment]
Hello There ! I encountered this error today.
After a bit experimenting with `neutralino.config.json` file, I've finally found cause this problem.
This error occurs when there is no `clientLibrary` field in `neutralino.config.json`. be sure to set this field, it should be pointing to the [client library](https://github.com/neutralinojs/neutralino.js)'s path.
I'm using my own client library and don't need neutralino to add it the source code again. so, in this case, i'm just using an empty JS file.

**Comment by beibeibeibei2022** [comment]
Hello! maybe neutralino.config.json problem.
i lost this, ```neutralino.config.json > modes > window > icon```.
You can refer to this document 👉 [neutralino.config.json from web-to-desktop-framework-comparison](https://github.com/Elanis/web-to-desktop-framework-comparison/blob/3f996e1cedf3da86ebafd08850357cf051649774/benchmark/01-empty-app/neutralinojs/neutralino.config.json)

**Comment by shalithasuranga** [comment]
This issue was fixed by https://github.com/neutralinojs/neutralinojs-cli/commit/39c925ab0593c5cf2f3b6ec6dc4c49de539ec7d1
We'll release these changes with the upcoming release :tada:
