### ISSUE TITLE
 Debug mode on server side (CLI) ?

### ISSUE THREAD

**Issue by serge-hulne** [neutralinojs/neutralinojs-cli#16]
I think a debug mode on the command line is needed to debug errors which are not related to the JS scripts (i.e. which are not "client-side"), but to anything else: e.g. : Configuration scripts (json files), for instance to avoid. 

For instance : a typo in config.json will make the executable fail silently (at least on Windows 10).

it could be passed as an option to the executable, lilke neutralino-win.exe --debug, for instance.

That's what a regular server does by default (Express, for instance).

**Comment by serge-hulne** [comment]
That would be absolutely brilliant !

Thanks.

Serge.

**Comment by shalithasuranga** [comment]
![image](https://user-images.githubusercontent.com/18402702/81953989-ef3e1100-9625-11ea-9429-ef7a42095b56.png)

Will be released with the next version

**Comment by serge-hulne** [comment]
Super !

Thanks a lot, this will prove very useful!

Serge.
