### ISSUE TITLE
neu patch

### ISSUE THREAD

**Issue by patarapolw** [neutralinojs/neutralinojs-cli#17]
Patch `/dist/index.html` with Neutralino JavaScript files and binaries.

My plan is to run these concurrently

- `vue-cli-service build --watch`
- `neu patch && neu run`

**Comment by shalithasuranga** [comment]
Hey.. Thanks for posting @patarapolw . Could you explain the goal of this one a bit :)

**Comment by patarapolw** [comment]
Use both Vue CLI and Neutralino; i.e. install Webpack first, neutralino later.

Which is very different from `neu create`.

**Comment by shalithasuranga** [comment]
Hey.. I think you are trying to use Vue hot reload with Neutralinojs? It's added with https://github.com/neutralinojs/neutralinojs-cli/issues/96 :) Please let us know if you meant another feature
