### ISSUE TITLE
Avoid using shell scripting syntax for cross-platform support

### ISSUE THREAD

**Issue by shalithasuranga** [neutralinojs/neutralinojs-cli#171]
Please consider changing the lines like these:

```js
let output = runner.run('cd test-app && neu build')
```

We can write something like:
```js
process.chdir('test-app');
let output = runner.run('neu build');
```

I think we can use `runner.run()` only for Neutralinojs commands to enable cross-platform support and better readability 

Assignee: @pathange-s

**Comment by pathange-s** [comment]
Good, thanks you pointed it out. Actually, I didn't really think of this as I got a confirmation from you that, we will need to run the test suite only on Linux. Well, this seems to be a valid issue, I will submit a pull request for the same.
