### ISSUE TITLE
Test the `neu update` command a little bit thoroughly 

### ISSUE THREAD

**Issue by shalithasuranga** [neutralinojs/neutralinojs-cli#173]
Right now, we simply check the output of the `neu update` command. Seems like we can check the functionality with the following steps:

- Update the client/server version in the config to a specific version
- Run `neu update`
- Test the version with `neu version`

Assignee @pathange-s

**Comment by pathange-s** [comment]
Okay, so you mean to check an update to a random version, right? Let me add this test case too.
