### ISSUE TITLE
Conflict Hot Reload with Neutralino native API

### ISSUE THREAD

**Issue by mp3846** [neutralinojs/neutralinojs-cli#177]
After enabling [Hot Reload](https://neutralino.js.org/docs/how-to/use-a-frontend-library#enabling-hot-reload) and running `neu run --frontend-lib-dev` _Hot Reloading_ works fine but I can not access global variables like `NL_OS` !

Here is the result of running [Demo](https://github.com/codezri/neutralinojs-react) project:

![Neutralino Hot Reload Conflict With Native API](https://user-images.githubusercontent.com/54330485/179204760-33b171e9-c947-49ed-a38b-8796b06aa0ff.gif)

After running `neu run --frontend-lib-dev --window-enable-inspector` I get this error in the console:

```
Uncaught DOMException: Failed to construct 'WebSocket': The URL 'ws://localhost:undefined' is invalid.
at a (http://localhost:3000/neutralino.js:1:580)
at e.init (http://localhost:3000/neutralino.js:1:11526)
at ./src/index.js (http://localhost:3000/static/js/bundle.js:105:19)
at options.factory (http://localhost:3000/static/js/bundle.js:45618:31)
at __webpack_require__ (http://localhost:3000/static/js/bundle.js:45063:33)
at http://localhost:3000/static/js/bundle.js:46200:37
at http://localhost:3000/static/js/bundle.js:46202:12
  ```  
   Every thing is OK when I just run `neu run` (native API is accessible)

**Comment by mp3846** [comment]
Any progress on resolving this bug : [#909](https://github.com/neutralinojs/neutralinojs/issues/909) ?

**Comment by Vexcited** [comment]
> Now we can access Neutralino API but still predefined global variables like `NL_OS` or `NL_CWD` are undefined!

I found a fix for Vite but you can edit my fix according to the build tool you're using.

**Comment by shalithasuranga** [comment]
I think you can solve the issue by using the `window.` prefix while accessing global variables. Please use the latest neu CLI version which doesn't ask you to manually use the `--frontend-lib-dev` flag. Thanks :tada:
