### ISSUE TITLE
NL_* vars not set in client when run with frontend-lib-dev flag

### ISSUE THREAD

**Issue by benoneal** [neutralinojs/neutralinojs-cli#179]
**Expected Behavior**  
All `NL_*` global vars should be set in the client regardless of cli flags.

**Actual Behavior**  
None of the `NL_*` global vars are set in the client when run with `--frontend-lib-dev` flag, despite being present when run with no flag. This results in none of the native API or any server-dependent Neutralino functionality working from the client, as the websocket cannot connect due to undefined `NL_PORT`. 

This makes development significantly slower and more frustrating as the client has to be re-built and the app re-run to test any functionality dependent on these features. 

**Steps to Reproduce the Problem**  
 1. Run a test app with `neu run`
 2. Confirm that `NL_PORT` (or any `NL_` prefixed global vars) is set either via enabling the inspector or having the client render it
 3. Run the same app with `neu run --frontend-lib-dev`
 4. Observe that `NL_PORT` (and all `NL_*` vars) is now undefined (and the websocket connection will have errored, rendering Neutralino broken entirely)

**Specifications**  
* NeutralinoJs Version: 4.4.0
* NeutralinoJs CLI version: 9.2.0
* Platform: macOS Monterey 12.1

**Comment by mkikets99** [comment]
Hi everyone
I am here to add that it is not only MacOS issue... I have same problem...
OS info:
**OS:** Linux
**Distro:** Arch/Garuda Linux
**Kernel Version:** 5.19.13 (x86_64)
**NEU-CLI version:** 
```
--- Global ---
neu CLI: v9.3.1

--- Project: **Censored** (js.neutralino.zero) ---
Neutralinojs binaries: v4.7.0
Neutralinojs client: v3.6.0
```
Tested repos:
codezri/neutralinojs-react
DEVLOPRR/react-neutralino
Self builded by tutorial on [Neutralino Docs](https://neutralino.js.org/docs/how-to/use-a-frontend-library)

Result:
`NL_*` variables appear when using `neu run` command, but not when `neu run --frontend-lib-dev`

**Comment by CuteCubed** [comment]
Have you guys tried to configure the Config Options "patchFile" and "devUrl" ? 
Eg:
![image](https://user-images.githubusercontent.com/31990756/201688985-cf0b88c8-ad06-469d-97ee-6574382ab646.png)

**Comment by CuteCubed** [comment]
Do you get the log output for the hotfix being applied?

**Comment by CuteCubed** [comment]
I created a little patch that changes the localhost to 0.0.0.0 after installing the module, it helped me to get the frontendLibrary to work. If you want to give it a try: [patch_install.js](https://gist.github.com/CuteCubed/87d3400a834b6a3a4a38122994fe5cb7)

**Comment by CuteCubed** [comment]
You have to install neutralino as a dev dependency like:
npm install --save-dev @neutralinojs/neu

or you can change the url by hand if you installed globally, the script will only change the dev dependency though

**Comment by shalithasuranga** [comment]
Please update the neu CLI program. Now we don't use the `--frontend-lib-dev` flag and implement a better integration with frontend library development servers :tada:
