### ISSUE TITLE
AuthInfo being exported even with `exportAuthInfo: false`

### ISSUE THREAD

**Issue by NemoStein** [neutralinojs/neutralinojs-cli#180]
**Describe the bug**
The `./.tmp/auth_info.json` file is always generated, ignoring the `exportAuthInfo` config property

**To Reproduce**
1. Set `"exportAuthInfo": false` in the `neutralino.config.json`
2. Run the app with `neu run`
3. The `./.tmp/` folder is created with a `auth_info.json` file inside

**Expected behavior**
No `./.tmp/` folder or `auth_info.json` file should be created

**Specifications**  
 - OS: Windows 10 x64
 - Neutralinojs version: v4.5.0
 - Neutralinojs v3.4.0
 - Neutralinojs CLI version: v9.3.0

**Comment by shalithasuranga** [comment]
Please note that the `neu run` command needs this `exportAuthInfo: true` configuration to properly connect with the Neutralinojs app, so the CLI program internally sets it. But, the production app won't automatically set this auth-related configuration.
