### ISSUE TITLE
Directly update binaries and client version to latest version

### ISSUE THREAD

**Issue by pathange-s** [neutralinojs/neutralinojs-cli#182]
- Instead of having to do : _Update the config file option cli.binaryVersion with 4.7.0 and enter neu update to fetch this version._  this after every new release, we can have a flag to `neu update` as `neu update --latest` to directly update the versions according to the latest available release.
- Updating to latest version is very common, so this would prove to be easy and helpful

**Comment by RS2007** [comment]
Hey, Are there any updates to this feature?

**Comment by AckerApple** [comment]
Hey so after a fresh install of a new neu project, my mac app files just work

PROBLEM: As soon as I run `neu update` my bin folder changes and the built apps won't open.

I wonder if this is related to the reported issue. That `neu update` does not truly give you the latest version

**Comment by shalithasuranga** [comment]
Hey all. This feature is implemented and will be released with the latest CLI release. Thanks for reporting and discussing :tada:
