### ISSUE TITLE
neutralino-linux_arm64

### ISSUE THREAD

**Issue by ca0v** [neutralinojs/neutralinojs-cli#194]
I cloned https://github.com/codezri/liteman to try on a Windows ARM64 in WSL, and received an error:

neu: INFO Error: ENOENT: no such file or directory, chmod 'bin/neutralino-linux_arm64'

I see that https://neutralino.js.org/docs/distribution/overview/ mentions "myapp-linux_arm64", so I was hoping it was possible to try out neutralino in a WSL environment on an ARM processor?

**Comment by shalithasuranga** [comment]
Hey @ca0v Thanks for reporting the issue. Seems like the liteman project still uses an older Neutralinojs version that doesn't support Linux ARM. Could you please update both server and client versions in `neutralino.config.json`, enter `neu update`, and try again :)
