### ISSUE TITLE
Doesnt' work on M1 Mac

### ISSUE THREAD

**Issue by jwalton** [neutralinojs/neutralinojs-cli#196]
Not sure if this is supposed to work out-of-the-box on M1 or not - I saw [this issue](https://github.com/neutralinojs/neutralinojs-cli/issues/66) and it's marked as resovled?

Anyways, if I try to follow along with the tutorial:

```sh
$ neu create myapp
...
$ cd myapp
$ new run
neu: INFO Error: ENOENT: no such file or directory, chmod 'bin/neutralino-mac_arm64'
```

I can work around it with `neu run --arch x64` to force it to run in Rosetta.

**Comment by ZCG-coder** [comment]
I think you'll have to compile https://github.com/neutralinojs/neutralinojs from source, then copy `bin/neutralino-mac_arm64` to your application's `bin` directory

**Comment by shalithasuranga** [comment]
Closing this since now Neutralinojs has a pre-built ARM binary with newer releases. Thanks for reporting and discussing :tada:
