### ISSUE TITLE
neu: ERROR Error: ENOENT: no such file or directory, stat 'bin/neutralino-linux_x64'

### ISSUE THREAD

**Issue by israeloriente** [neutralinojs/neutralinojs-cli#205]
I am trying to build a Angular App and already did the setup `url`, `resourcesPath`
After running `neu build` I got  "no such file or directory, stat 'bin/neutralino-linux_x64'"

neu: INFO Bundling app...
neu: INFO Generating resources.neu...
neu: INFO Copying binaries...
neu: ERROR Error: ENOENT: no such file or directory, stat 'bin/neutralino-linux_x64'
  _   _            _             _ _             _     
 | \ | | ___ _   _| |_ _ __ __ _| (_)_ __   ___ (_)___ 
 |  \| |/ _ \ | | | __| '__/ _` | | | '_ \ / _ \| / __|
 | |\  |  __/ |_| | |_| | | (_| | | | | | | (_) | \__ \
 |_| \_|\___|\__,_|\__|_|  \__,_|_|_|_| |_|\___// |___/
                                              |__/     
neu: INFO Application package was generated at the ./dist directory!
neu: INFO Distribution guide: https://neutralino.js.org/docs/distribution/overview

**Comment by shalithasuranga** [comment]
Hi.. thanks for reporting this issue. Please follow the new documentation (https://neutralino.js.org/docs/getting-started/using-frontend-libraries) to properly integrate a frontend framework/library with Neutralinojs.

Thanks :tada:
