### ISSUE TITLE
[error code 3221225781] neu run doesnt work

### ISSUE THREAD

**Issue by expertchi** [neutralinojs/neutralinojs-cli#211]
So, I followed every exact step of getting started with the first [app](https://neutralino.js.org/docs/getting-started/your-first-neutralinojs-app).

And then, when I ran `neu run`, it produced this output:
`neu: INFO Starting process: neutralino-win_x64.exe --load-dir-res --path=. --export-auth-info --neu-dev-extension --neu-dev-auto-reload`
`neu: WARNING neutralino-win_x64.exe was stopped with error code 3221225781`

To be sure, I also have nearly all VC redistributables installed with latest WebView2.
OS: Windows 10 22H2 Build: 19045.3086

**Comment by KontrollFreek** [comment]
I've found this only happens when neutralino-win_x64.exe is corrupted or not working properly. I fixed it by copying all my changed files to a new directory, deleting the project folder, re-creating the project, and replacing the files.

**Comment by viralgupta** [comment]
you could try updating the binaries using `neu update`
this will update the existing binaries used to run the project.

**Comment by expertchi** [comment]
> I've found this only happens when neutralino-win_x64.exe is corrupted or not working properly. I fixed it by copying all my changed files to a new directory, deleting the project folder, re-creating the project, and replacing the files.

This was it!
