### ISSUE TITLE
Frontend Dev wait for on different port

### ISSUE THREAD

**Issue by thorin8k** [neutralinojs/neutralinojs-cli#223]
I've been having problems with developing since the latest changes in the devCommand and frontendDev.

My problem is i'm not running the frontend in the port 3000 and even if i set a customized devUrl the system is trying to use the port 3000.

I've found that in the `frontendlib.js` file, the wait code is as follows:
![image](https://github.com/neutralinojs/neutralinojs-cli/assets/50626175/dbe02821-b419-4fdf-aa67-93855f6b7aa3)

As you see, the port variable is not used correctly.

**Comment by shalithasuranga** [comment]
Hello @thorin8k, thanks for posting this. If you don't use a frontend library, I think you can get your app working properly if you remove the `cli.frontendLibrary` section from the configuration :)

Please check and let us know :tada:

**Comment by thorin8k** [comment]
The way that i made it work was by changing my frontend dev environment to the port 3000. 

I think that this is the only solution because the port is hardcoded in the frontendLib of the client.

**Comment by shalithasuranga** [comment]
Closing this since it was fixed by #226. Thanks for reporting this :tada:
