### ISSUE TITLE
"neu run" command no auto reloading app

### ISSUE THREAD

**Issue by Eliezer516** [neutralinojs/neutralinojs-cli#234]
When starting the application with the **neu run** command, the application is deployed, but when making changes to the resources, the interface is not updated automatically. even right clicking and pressing reload the application does not refresh. In addition to the fact that in the terminal it does not reflect any error, on the contrary the messages show that everything is going well.

**Comment by skushagra9** [comment]
I am interested to work on this issue

**Comment by jerrygreen** [comment]
Please use any framework supporting hot-reload, like Svelte, or any bundler, it should handle auto-reloading like no problem.

It's not Neutralino who should be responsible for hot-reloading.

**Comment by Eliezer516** [comment]
In case you are interested, I solved the problem, you just have to add `Neutralino.init()` at the end of the main.js file and that's it, the application reloads when making any changes to the code
