### ISSUE TITLE
neu update should update the neutralino.js file as well

### ISSUE THREAD

**Issue by hschneider** [neutralinojs/neutralinojs-cli#247]
**Is your feature request related to a problem? Please describe.**
The current situation is that the nightly built brings breaking changes to the extension binding, which goes into the Neutralino binaries and the neutralino.js file. It is not possible to update to a complete nightly build via `neu update` because the js-file remains the old one.

**Describe the solution you'd like**
`neu update` should update neutralino.js as well.

**Describe alternatives you've considered**
A hint to update neutralino.js manually at the end of the update process.

**Additional context**
https://github.com/neutralinojs/neutralinojs/issues/1191

**Comment by shalithasuranga** [comment]
Hello, the `neu update` command typically updates the client library (`neutralino.js`) if the following criterias are ok:

1. `cli.clientLibrary` has the path of the `neutralino.js` file
2. `cli.clientVersion` has the version that you need (i.e., `nightly`)

However, you can get the latest client version (and the framework version as well) immediately  by entering the `neu update --latest` command.

We can re-open this issue if the issue really exists even after double-checking based on this comment's guide :) Thanks
