### ISSUE TITLE
Add option to `neu build` to clean/not clean build directory

### ISSUE THREAD

**Issue by ArcticFqx** [neutralinojs/neutralinojs-cli#258]
`neu build` at version 11.0.0 used to not clean the build directory, but the 11.0.1 update started doing that automatically with no option to turn that behavior off.

This unfortunately broke the build process of all my Neutralino projects as the build directory had intermediate build files which Neutralino is supposed to consume.

I propose that a CLI flag or that a flag in `neutralino.config.json` is added to control this behavior.

**Comment by Sadaf-A** [comment]
> `neu build` at version 11.0.0 used to not clean the build directory, but the 11.0.1 update started doing that automatically with no option to turn that behavior off.
> 
> This unfortunately broke the build process of all my Neutralino projects as the build directory had intermediate build files which Neutralino is supposed to consume.
> 
> I propose that a CLI flag or that a flag in `neutralino.config.json` is added to control this behavior.

Hey, thanks for pointing this out I have opened a PR which adds a CLI flag for this

**Comment by shalithasuranga** [comment]
Thanks so much for reporting this issue and working on it. This is fixed via #259 and changes will be released with the next CLI release soon :tada:
