### ISSUE TITLE
Websocket error on handshake

### ISSUE THREAD

**Issue by ChevalMonsieur** [neutralinojs/neutralinojs-cli#273]
**Describe the bug**
With the react template mentionned on the Neutralino website : ["codezri/neutralinojs-react"](https://github.com/codezri/neutralinojs-react), the websocket fail to connect when launching the webapp.

**To Reproduce**
1. on a terminal, do this command ```neu create myapp --template codezri/neutralinojs-react``` then ```cd myapp```
2. still on the terminal, do ```neu run -- --window-enable-inspector```
4. on the window inspector, check that you have an error either like "WebSocket connection to 'ws://localhost:XXXXX/' failed: The server did not accept the WebSocket handshake." or like "Invalid url for WebSocket ws://localhost:undefined"

**Expected behavior**
The app should launch without error and the websocket connection should be ok

**Screenshots/Screen recordings**
![image](https://github.com/neutralinojs/neutralinojs/assets/126174925/93a7b693-4ef0-4c2b-ba85-d2c4e513ad6c)
![image](https://github.com/neutralinojs/neutralinojs/assets/126174925/1b9e56f1-8726-4bb1-9d9d-7b278d3ad2b1)

**Specifications**  
 - OS: Ubuntu 22.04.4
 - Neutralinojs version: v5.1.0
 - Neutralinojs client library version: ?
 - Neutralinojs CLI version: 11.0.1

**Comment by shalithasuranga** [comment]
This issue was fixed and will be released with the next version soon!. Thanks for reporting and starting a discussion :tada:
