### ISSUE TITLE
Packager like electron-builder

### ISSUE THREAD

**Issue by pzeinlinger** [neutralinojs/neutralinojs-cli#28]
Is there any ongoing work towards a packager that bundles the executable and the source code into a single file?

**Comment by shalithasuranga** [comment]
Yeah.. now we are adding asar bundling support for resources.. initial version will be release soon

**Comment by shalithasuranga** [comment]
More info: https://github.com/neutralinojs/neutralinojs/issues/362

**Comment by shalithasuranga** [comment]
Now njs apps can be bundled into one resource file + binaries
