### ISSUE TITLE
React Typescript Template

### ISSUE THREAD

**Issue by yigitlevent** [neutralinojs/neutralinojs-cli#33]
I have been trying to figure out how to setup a React-Typescript project today. I thought opening this issue may bring the point up and maybe something like `--template ts-react` may be added. I'm not sure how problematic that'd be but for someone like me who creates projects very often for various work-related stuff, having this shorthand would be invaluable and time-saving.

**Comment by yigitlevent** [comment]
Any updates or pointers for this? I'd love to hear how to add typescript to the react template (or vice versa) for example.

**Comment by shalithasuranga** [comment]
Hey.. Thanks for reporting this. I am closing this because we only support one minimal template right now.. Please check https://youtu.be/4WAur8r7Jhk and see how you can use any frontend framework with Neutralinojs.
