### ISSUE TITLE
A Vue-cli plugin ?

### ISSUE THREAD

**Issue by deka** [neutralinojs/neutralinojs-cli#38]
Hi,
Nice job.
Do you plan to easily use  neutralinojs with vue and vue cli ?
Actually we use VueJs, and Vue Cli, but folder structure not working with your.

A vue cli plugin would be a good starting point to increase adoption of neutralinojs in vue world.
[https://cli.vuejs.org/dev-guide/plugin-dev.html](https://cli.vuejs.org/dev-guide/plugin-dev.html)

Something like electron builder plugin : 
[https://nklayman.github.io/vue-cli-plugin-electron-builder/](https://nklayman.github.io/vue-cli-plugin-electron-builder/)

**Comment by shalithasuranga** [comment]
Hey.. please check https://github.com/yooneskh/vite-neutralinojs-template. Likewise, we can use any frontend framework with Neutralinojs. More info: https://neutralino.js.org/docs/configuration/project-structure
