### ISSUE TITLE
ERROR: 'neu listen' EADDRINUSE: address already in use :::8080

### ISSUE THREAD

**Issue by holmesadrianh** [neutralinojs/neutralinojs-cli#40]
When trying to run `neu listen` I get an error:

`Error: listen EADDRINUSE: address already in use :::8080`

I require that port for another application. Is it possible to change the port being used?

**Comment by shalithasuranga** [comment]
ah, currently dev server uses 8080. I will add an option to provide the port soon eg: `neu listen --port 5000`. For now, you can change it yourself  by changing port here https://github.com/neutralinojs/neutralinojs-cli/blob/8f8b42a67db4c854c13ecf30836fcdc3152b4d85/src/modules/devserver.js#L3

**Comment by shalithasuranga** [comment]
Hey.. I am closing this because now the dev server is using 5050 port by default.
