### ISSUE TITLE
neu version

### ISSUE THREAD

**Issue by DavidLibeau** [neutralinojs/neutralinojs-cli#48]
Add a `neu version` command that only print the currently installed version of Neutralino.

**Comment by shalithasuranga** [comment]
@DavidLibeau  Thanks for this idea. `neu version` is available with the latest CLI.
![image](https://user-images.githubusercontent.com/18402702/122424745-98370800-cfac-11eb-9f4f-def869cfe229.png)

**Comment by shalithasuranga** [comment]
Please note that this command shows currently installed module versions. I added [this](https://github.com/neutralinojs/neutralinojs-cli/issues/51) issue to extend this to display versions of the current project as well because someone can run `neu version` on a bit old project.
