### ISSUE TITLE
`neu build` should create a `dist` directory

### ISSUE THREAD

**Issue by patarapolw** [neutralinojs/neutralinojs-cli#5]
This CLI is not good. I had to download directly from [/releases](https://github.com/neutralinojs/neutralinojs/releases).

IMO, CLI should hide the implementation, and do not pre-generate too many files. `neu build` (and `neu dev`) instead, should generate needed files.

However, I made a set of scripts in <https://github.com/patarapolw/neutralino-vue/tree/master/packages/app> that can serve as a guideline for better CLI.

**Comment by shalithasuranga** [comment]
Hey.. Thanks for the ideas .. `neu build` is basically to transpile stuff and make minified js. Your idea will be implemented with `neu release` https://github.com/neutralinojs/neutralinojs-cli/issues/10

**Comment by shalithasuranga** [comment]
`neu-release` will make a zip
