### ISSUE TITLE
ES6 module template

### ISSUE THREAD

**Issue by 54696d654a6f6c74** [neutralinojs/neutralinojs-cli#50]
As of now, only a "minimal" template can be generated, which consists of a `var` library from https://github.com/neutralinojs/neutralino.jshttps://github.com/neutralinojs/neutralino.js generated by webpack hosted on
 https://github.com/neutralinojs/neutralinojs-minimal.

A "module" template can be created from the same source by editing the webpack config, and hosted as "neutralinojs-module". This template will allow selective imports from the Neutrino API instead of loading the entire library through a `<script>` tag.

If these changes are approved, I'll make a PR.

**Comment by shalithasuranga** [comment]
Closing this since now we have a published NPM module (`@neutralinojs/lib`). Thanks for reporting this issue :tada:
