### ISSUE TITLE
EACCES permission denied, syscall: copyfile when "neu build --release"

### ISSUE THREAD

**Issue by CM-IV** [neutralinojs/neutralinojs-cli#59]
## Greetings neutralinojs team

This problem is most likely entirely my fault, however I'd like another pair of eyes on it.

I have a working desktop application as the screenshot shows:

![Screenshot from 2021-07-10 22-17-22](https://user-images.githubusercontent.com/44551614/125181675-cf27c480-e1cc-11eb-8962-50fe3ac8c1c5.png)

However, the issue occurs upon executing the CLI command:
> neu build --release

I receive the below EACCES permission denied error:

![Screenshot from 2021-07-10 22-24-41](https://user-images.githubusercontent.com/44551614/125181749-a6ec9580-e1cd-11eb-8b74-0a837cadf958.png)

I cannot seem to copy over the Linux binaries..

A temp folder is created that is an exact copy of the /frontend/ folder.

You can also see in the folder directory that I am not using the /resources/ folder, and have instead created my own /frontend/ folder.

I will also include an image of my config file:

![Screenshot from 2021-07-10 22-27-09](https://user-images.githubusercontent.com/44551614/125181791-fb901080-e1cd-11eb-9b8e-cbb71b7259b7.png)

I cannot seem to fix this issue, another opinion on the subject would be of great help to me.

**Comment by shalithasuranga** [comment]
Hey.. applied a fix for this issue with the latest version. Please check.
