### ISSUE TITLE
Neu Run Returns Error Unsupported Platform

### ISSUE THREAD

**Issue by danidre14** [neutralinojs/neutralinojs-cli#67]
**Expected Behavior**  
Typing the neu run command should let the application be run locally (without building).
  
**Actual Behavior**  
An error is returned:
![image](https://user-images.githubusercontent.com/10374096/133917395-acca82f6-3257-478a-876c-da34addb7eb0.png)
It says something about win32_ia32 which I think means ia32 is 32bit node. However, do note that I have a 64bit computer:
![image](https://user-images.githubusercontent.com/10374096/133917539-2d14d038-7b61-495a-97e3-0ae5301d68d2.png)

**Steps to Reproduce the Problem**  
No clue. neu run worked all the time, but after I updated to the version stated below, this suddenly began happening.

**Specifications**  
* NeutralinoJs Version: binary: 2.7.0; client: 1.4.0
* NeutralinoJs CLI version: 6? no clue how to find this 
* Platform: Windows 10 64-bit (see photo above)

**Comment by danidre14** [comment]
Previous versions of neu worked fine on my 32bit Nodejs version. How is it that the architecture has now changed? Do I need to upgrade to a 64 bit now?

**Comment by shalithasuranga** [comment]
Hey.. We've applied a patch for it. Please use `neu run --arch=x64` with @neutralinojs/neu@6.2.1 . --arch option allows us pass custom architecture because we can rely on process.arch from Nodejs.

**Comment by danidre14** [comment]
Okay, noted.
I have already uninstalled NodeJS and reinstalled the 64 bit Nodejs, so I will not be able to test whether this solution works.
However, thank you for the fix and feature.
