### ISSUE TITLE
neu run --mode=browser. Ignores the requested mode

### ISSUE THREAD

**Issue by baselakasha** [neutralinojs/neutralinojs-cli#69]
Hello, 

I am trying to use `neu run` and supply the mode I need to use. But it seems that the supplied mode gets ignored and it uses whatever the default mode specified in the config file. 

The command I am using:  `neu run --mode=browser`

I tried with node versions 14.15.4 and 16.1.0 both have the same result.

**Comment by shalithasuranga** [comment]
Please check with `@neutralinojs/neu@6.2.2`. There was a bug with `neu run --mode` and now it's fixed.
