### ISSUE TITLE
Implement neu listen

### ISSUE THREAD

**Issue by shalithasuranga** [neutralinojs/neutralinojs-cli#7]
`neu listen` will check for changes and automatically execute `neu build`

**Comment by EriKWDev** [comment]
I suppose the initial solution is to rebuild the entire app upon any changes. It would however be a much nicer solution if for example minor changes like editing text in html or styles from css could just be "injected" into the app without having to rebuild everything, and only rebuild if the developer wants to through something like "ctrl + shift + r".

For anyone looking for a workaround in the meantime you can use `nodemon` with something like `nodemon -x "neu build && neu run" -w src/*` which listens to changes in the src folder and rebuilds and launches when detected.

Is there any ETA on `neu listen`? :)

**Comment by shalithasuranga** [comment]
Hey.. @EriKWDev Yeah I thought about just refreshing the app for now. Like you mentioned smart reload looks great.. I am now adding simple reload first then we could improve it using something like nodemon guess..

**Comment by shalithasuranga** [comment]
Closed this since it is added to neu-cli (but not released). I will release this soon with Neutralinojs v1.7.0.
