### ISSUE TITLE
How to Change .exe description name in Task Manager?

### ISSUE THREAD

**Issue by Goyp95** [neutralinojs/neutralinojs-cli#70]
How to change [Neutralinojs binary for Windows] this name to myApp name in Task Manager..thats all.

Neutralinojs binaries: v2.7.0
Neutralinojs client: v1.4.0
neu CLI: v6.1.0
Window 10

**Comment by shalithasuranga** [comment]
Hey.. all thanks for discussing and reporting this issue. Right now, we are not planning to extend the CLI by adding a resource editor for Windows. We hope someday the community will make a resource editor tool. I would like to suggest https://github.com/electron/rcedit for resource editing at this stage of Neutralinojs development.
