### ISSUE TITLE
High Severity Vulnerability: Prototype Pollution in set-value

### ISSUE THREAD

**Issue by SuperPhatArrow** [neutralinojs/neutralinojs-cli#73]
```
# npm audit report

set-value  <4.0.1
Severity: high
Prototype Pollution in set-value - https://github.com/advisories/GHSA-4jqc-8m5r-9rpr
fix available via `npm audit fix --force`
Will install @neutralinojs/neu@1.3.0, which is a breaking change
node_modules/set-value
  edit-json-file  *
  Depends on vulnerable versions of set-value
  node_modules/edit-json-file
    @neutralinojs/neu  >=1.4.0
    Depends on vulnerable versions of edit-json-file
    node_modules/@neutralinojs/neu

3 high severity vulnerabilities
```

Suggested fix:
`neu` should update dependency `edit-json-file` from `>=1.4.0` to `>=1.6.0` which depends on fixed version of `set-value` `>=4.0.1`

**Comment by shalithasuranga** [comment]
Hey Thanks for the notification. Looks like 1.6.0 still uses the vulnerable child package. Maybe we can wait a bit until the package maintainer publishes a new version. If it won't happen soon, we can add a fix to override the version of the nested dependency.

**Comment by SuperPhatArrow** [comment]
Hi, thanks for the quick response.

It looks to me like 1.6.0 uses 4.0.1 in the package.json:
https://github.com/IonicaBizau/edit-json-file/blob/657a14216df2e8d97547d6e9557a594db618aae1/package.json#L46

As of this commit:
https://github.com/IonicaBizau/edit-json-file/commit/0a522ad61b5b0650803c5af039a769e7c6c4f1ef

I do appreciate your note that neu is unaffected by this vulnerability (I hadn't looked that deeply into your code, to be honest) but just thought that a simple version bump would remove the scary NPM warning when installing the CLI globaly.

PS Thanks for the project, NeutralinoJS is very cool!

**Comment by shalithasuranga** [comment]
Hey.. thanks for checking it further. Yeah, the lib's repo is updated but not yet published guess. Looks like the latest release came before the commit you mentioned :)

**Comment by SuperPhatArrow** [comment]
OK, I see, thanks for explaining. I have raised an issue requesting a new release.

https://github.com/IonicaBizau/edit-json-file/issues/47

**Comment by shalithasuranga** [comment]
Great.. Thanks and welcome

**Comment by SuperPhatArrow** [comment]
@shalithasuranga v1.6.2 is now released with the updated dependency.

**Comment by shalithasuranga** [comment]
Hey.. v7.0.1 published with the updated lib.. Thanks for the support @SuperPhatArrow :rocket:
