### ISSUE TITLE
Have installed Neutralino, but get an error on the "Downloading the Neutralinojs client" part when using 'neu create mynewproject'

### ISSUE THREAD

**Issue by shadowsocksquestions** [neutralinojs/neutralinojs-cli#75]
I'm wondering if others have this problem, if there's a fix or if there's a workaround (I see it mentioned (https://neutralino.js.org/docs/getting-started/your-first-neutralinojs-app/#!) that it's possible to create a project without the CLI, but couldn't find any info on it...does anyone have of example/an empty project structure I could create, if it's simply the project setup that has gone wrong, rather than any more fundamental part of the Neutralino code being missing)

So I was able to install with sudo using:

`**sudo** npm install -g @neutralinojs/neu`

I then tried the following command:

`neu create mynewproject`

but got this output

```
Downloading minimal template to mynewprojectdirectory...
Extracting template zip file..
Downloading Neutralinojs binaries..
Extracting zip file..
Finalizing and cleaning temp. files.
Downloading the Neutralinojs client..
events.js:292
      throw er; // Unhandled 'error' event
      ^

Error: read ECONNRESET
    at TLSWrap.onStreamRead (internal/stream_base_commons.js:205:27)
Emitted 'error' event on Writable instance at:
    at ClientRequest.eventHandlers.<computed> (/usr/local/lib/node_modules/@neutralinojs/neu/node_modules/follow-redirects/index.js:14:24)
    at ClientRequest.emit (events.js:315:20)
    at TLSSocket.socketErrorListener (_http_client.js:426:9)
    at TLSSocket.emit (events.js:315:20)
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  errno: 'ECONNRESET',
  code: 'ECONNRESET',
  syscall: 'read'
}
```

Thanks in advance if anyone can help :)

**Comment by shalithasuranga** [comment]
Closing this one since this issue is no longer happening. Hey @dubiao  we used git clone option before, but we had to download the template directly as a zip file since the cloning process becomes too slow when the commit count grows. Thanks for the idea. Please check the latest version and let us know if there is any issue with `neu create`
