### ISSUE TITLE
Typescript definitions

### ISSUE THREAD

**Issue by corbane** [neutralinojs/neutralinojs-cli#79]
Hello,

Maybe it would be good to include the Typescript definitions in the "create" command.

**Comment by shalithasuranga** [comment]
Hey.. thanks for the suggestion. Do you mean the TypeScript definitions of the `create` command helpful for plugin developers? or any other use case?

**Comment by corbane** [comment]
Hello @shalithasuranga 

For everyone,
I created a project yesterday with `neu create`. I expected to find `neutralino.d.ts` in the `resources` folder.
This allows you to have typechecking when editing `main.js`,

**Comment by shalithasuranga** [comment]
Ah got it .. nice idea. Yeah it will be helpful for devs who use Angular etc also guess

**Comment by YashKumarVerma** [comment]
do we still have this in the picture? If yes, should I move ahead for the same? If no, can we mark this as stale?

cc @shalithasuranga

**Comment by alsuren** [comment]
I threw together a fix for this in #219 . I'm not familar with this codebase though, so I'd like feedback on how/whether to make it opt-in.
