### ISSUE TITLE
Icon is not added in exe

### ISSUE THREAD

**Issue by LTVA1** [neutralinojs/neutralinojs-cli#84]
**Expected Behavior**  
Icon is added to an exe in dist folder.
  
**Actual Behavior**  
Icon is not added to an exe in dist folder. 

**Steps to Reproduce the Problem**  
 1. Create a template app using instruction in readme
 2. Use [this](https://gitlab.com/fractalsLTVA/fractals/-/blob/main/example.zip) as source
 3. `neu build`

**Specifications**  
* NeutralinoJs Version: 4.0.0
* NeutralinoJs CLI version: 8.0.0
* Platform: Windows 10 x64

My theory is that maybe I have smth wrong in config, but I haven't changed anything related to icons and it worked by default in 3.0.0.

![This is an image](https://cdn.discordapp.com/attachments/771372893123772426/920699549713039372/unknown.png)

**Comment by shalithasuranga** [comment]
Hey.. all thanks for discussing and reporting this issue. Right now, we are not planning to extend the CLI by adding a resource editor for Windows. We hope someday the community will make a resource editor tool with Neu CLI extensions. I would like to suggest https://github.com/electron/rcedit for resource editing at this stage of Neutralinojs development.

**Comment by CosmoMyzrailGorynych** [comment]
Happy to announce that .exe files will have proper icons and more in the upcoming neutralino-cli version that will include my PR https://github.com/neutralinojs/neutralinojs-cli/pull/268 🎉
