### ISSUE TITLE
Question: How to build using script?

### ISSUE THREAD

**Issue by NightyLighty** [neutralinojs/neutralinojs-cli#86]
Can I build neutralinojs app without using script without using script?
For example
```javascript
Neutralino.build(targetFolder);
```
Is there a function like this?
Is it possible?

**Comment by shalithasuranga** [comment]
Hey.. could you please let us know why you need this way of bundling app - so we can give you some ideas. Application bundling is a part of CLI. However, as we mentioned in docs, the CLI is optional. You can simply use [asar](https://github.com/electron/asar) to pack resources directly. I think you are trying to generate the app automatically. If yes, I would suggest you write a CLI plugin and use [bundler.js](https://github.com/neutralinojs/neutralinojs-cli/blob/master/src/modules/bundler.js) via the plugin. Also, it's possible to write an automation script to trigger `neu build` too.
