### ISSUE TITLE
Package as AppImage

### ISSUE THREAD

**Issue by locriacyber** [neutralinojs/neutralinojs-cli#88]
If Neutralino is packaged as AppImage (for Linux), it will not need the application developer to install the dependencies separately.

appimagetool: https://appimage.github.io/appimagetool/
Documentaiton: https://github.com/AppImage/AppImageKit#appimagetool-usage

Before we package Neutralino, we need to make `neutralino-linux_x64` a standalone executable that accepts command line arguments first.

**Comment by locriacyber** [comment]
TODO
- [ ] make neutralino.config.json location configurable as CLI argument
- [ ] package as AppImage

**Comment by shalithasuranga** [comment]
Hey.. I haven't tried testing with AppImage yet, but I think `--path=<path>` will probably solve the first TODO item ;) I will create AppImage and let you know more info. Thanks

**Comment by shalithasuranga** [comment]
Hey.. all thanks for discussing and reporting this issue. Right now, we are not planning to extend the CLI by adding an AppImage creator. However, you can use Neutralinojs community projects like https://github.com/krypt0nn/neutralino-appimage-bundler for bundling AppImages
